[workspace]
resolver = "2"
members = ["crates/glint", "crates/glide", "crates/glint-core", "crates/glide-shell"]

[workspace.dependencies]
glint-core = { path = "crates/glint-core" }
egui = "0.33.3"
eframe = "0.33.3"
anyhow = "1.0.104"
open = "5.4.0"
winreg = "0.56.0"
raw-window-handle = "0.6"
log = "0.4.33"
env_logger = "0.11.11"
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_System_Com",
    "Win32_System_Ole",
    "Win32_UI_Shell_Common",
    "Win32_System_LibraryLoader",
    "Win32_Storage_FileSystem",
    "Win32_System_SystemServices",
    "Win32_System_Registry",
    "Win32_System_Pipes",
    "Win32_System_IO",
    "Win32_Security",
    "Foundation",
    "Foundation_Collections",
    "ApplicationModel",
    "UI_Notifications",
    "UI_Notifications_Management",
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_DirectComposition",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_Threading",
    "Win32_System_DataExchange",
    "Win32_System_Power",
    "Win32_System_Shutdown",
    "Win32_Media_Audio",
    "Win32_Media_Audio_Endpoints",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Variant",
    "Win32_UI_Input_Ime",
    "Win32_Networking_NetworkListManager",
    "Win32_NetworkManagement_WiFi",
    "Win32_NetworkManagement_Ndis",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_Devices_FunctionDiscovery",
    "Win32_System_Environment",
    "Win32_Graphics_Imaging",
    "Win32_System_Wmi",
] }
windows-core = "0.62"
windows-numerics = "0.3"

[profile.release]
opt-level = "s"
lto = true
strip = true
panic = "abort"
codegen-units = 1
